import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  // {
  //   path: '',
  //   title: '-- Main',
  //   iconType: '',
  //   icon: '',
  //   class: '',
  //   groupTitle: true,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
  {
    path: 'dashboard/main',
    title: 'Home',
    iconType: 'material-icons-outlined',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: 'Master Menu',
    iconType: 'material-icons-outlined',
    icon: 'description',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'travel-category',
        title: 'Travel Category',
        iconType: 'material-icons-outlined',
        icon: 'view_list  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'stay-category',
        title: 'Stay Category',
        iconType: 'material-icons-outlined',
        icon: 'business  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      // {
      //   path: '/trip-duration',
      //   title: 'Trip Duration',
      //   iconType: 'material-icons-outlined',
      //   icon: 'event_note  ',
      //   class: '',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   submenu: [],
      // },
    ],
  },
  {
    path: '',
    title: 'Tour Package',
    iconType: 'material-icons-outlined',
    icon: 'description',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'destination',
        title: 'Destination',
        iconType: 'material-icons-outlined',
        icon: 'location_on  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'destination-route',
        title: 'Destination Route ',
        iconType: 'material-icons-outlined',
        icon: 'location_on  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'manage-hotels',
        title: 'Manage Hotels ',
        iconType: 'material-icons-outlined',
        icon: 'business ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'trip-packages',
        title: 'Trip Packages',
        iconType: 'material-icons-outlined',
        icon: 'event_note  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'tour-package-reviews',
        title: 'Reviews',
        iconType: 'material-icons-outlined',
        icon: 'review  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'trip-faq',
        title: 'FAQ',
        iconType: 'material-icons-outlined',
        icon: 'faq  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ]
  },
  {
    path: 'query-leads',
    title: 'Query Leads',
    iconType: 'material-icons-outlined',
    icon: 'view_list  ',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'query-leads/open',
        title: 'Open Leads',
        iconType: 'material-icons-outlined',
        icon: '',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'query-leads/hold',
        title: 'Hold Leads',
        iconType: 'material-icons-outlined',
        icon: '',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'query-leads/canceled',
        title: 'Canceled Leads',
        iconType: 'material-icons-outlined',
        icon: '',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }
    ],
  },
  {
    path: 'quotation-request',
    title: 'Quotation',
    iconType: 'material-icons-outlined',
    icon: 'view_list  ',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'booking-list',
    title: 'Booking List',
    iconType: 'material-icons-outlined',
    icon: 'view_list',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'booking-list',
        title: 'All List',
        iconType: 'material-icons-outlined',
        icon: 'view_list  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'booking-list-success',
        title: 'Success Payments',
        iconType: 'material-icons-outlined',
        icon: 'view_list  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'booking-list-partial',
        title: 'Partial Payments',
        iconType: 'material-icons-outlined',
        icon: 'view_list  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'booking-list-failed',
        title: 'Failed Payments',
        iconType: 'material-icons-outlined',
        icon: 'view_list  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'booking-list-completed',
        title: 'Completed Booking',
        iconType: 'material-icons-outlined',
        icon: 'view_list  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }
    ]
  },
  {
    path: 'payment-history',
    title: 'Payment History',
    iconType: 'material-icons-outlined',
    icon: 'view_list  ',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
   {
    path: 'account-ledger',
    title: 'Account Ledger',
    iconType: 'material-icons-outlined',
    icon: 'view_list',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'account-ledger/office-expense',
        title: 'Office Expense',
        iconType: 'material-icons-outlined',
        icon: 'business  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'account-ledger/ledger-list',
        title: 'Ledger List',
        iconType: 'material-icons-outlined',
        icon: 'business  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }
    ],
  },
  {
    path: 'promo--codes',
    title: 'Promo Codes',
    iconType: 'material-icons-outlined',
    icon: 'view_list',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'promo-code/youtuber',
        title: 'Youtuber',
        iconType: 'material-icons-outlined',
        icon: 'business  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'promo-codes/manage',
        title: 'Promo Codes',
        iconType: 'material-icons-outlined',
        icon: 'business  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }
    ],
  },  
  {
    path: 'service-provider',
    title: 'Service Provider',
    iconType: 'material-icons-outlined',
    icon: 'view_list  ',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'booking-service-type',
        title: 'Service Type',
        iconType: 'material-icons-outlined',
        icon: '',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'booking-service-providers',
        title: 'Service Providers',
        iconType: 'material-icons-outlined',
        icon: '',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }
    ],
  },

  // {
  //   path: '/role-permission',
  //   title: 'Role Permission',
  //   iconType: 'material-icons-outlined',
  //   icon: 'view_list  ',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
  {
    path: 'blog',
    title: 'Blog',
    iconType: 'material-icons-outlined',
    icon: 'view_list  ',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'event',
    title: 'Event',
    iconType: 'material-icons-outlined',
    icon: 'view_list  ',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'faq',
    title: 'FAQ',
    iconType: 'material-icons-outlined',
    icon: 'view_list  ',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'testimonial',
    title: 'Testimonial',
    iconType: 'material-icons-outlined',
    icon: 'view_list  ',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'static-page-seo',
    title: 'Static Page Seo',
    iconType: 'material-icons-outlined',
    icon: 'view_list  ',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'users',
    title: 'Users',
    iconType: 'material-icons-outlined',
    icon: 'people  ',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'admin-list',
    title: 'Admin Users',
    iconType: 'material-icons-outlined',
    icon: 'people  ',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'api-logs',
    title: 'API Logs',
    iconType: 'material-icons-outlined',
    icon: 'view_list',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'admin-api-logs',
        title: 'Admin Logs',
        iconType: 'material-icons-outlined',
        icon: 'view_list  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'web-api-logs',
        title: 'Web Logs',
        iconType: 'material-icons-outlined',
        icon: 'business  ',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }
    ],
  }
];
